### ISSUE TITLE
Notifications color is white instead of inverted colors or black colour

### ISSUE THREAD

**Issue by hrithikb** [DVDAndroid/Xposed-EnableAmbientDisplay#3]

**Comment by DVDAndroid** [comment]
Have you tried to change alpha?

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QSjlMUXoxeFBnNkU/view?usp=drivesdk
See, this is happening I'm on aicp10

**Comment by DVDAndroid** [comment]
Try to disable AndroidN-ify module and tell me if this bug persist

**Comment by hrithikb** [comment]
Is it possible to have both module? I think this problem is by n ify but when i was on other roms like official cm12.1, rr, blisspop it was working good there!

**Comment by DVDAndroid** [comment]
Yes, and I think that the Ambient Display of Android Nougat it's the same as the module

**Comment by hrithikb** [comment]
Now ni fy is disabled but still getting this issue!
I think this problem's with aicp 10 only
