### ISSUE TITLE
Nothing on G 2015

### ISSUE THREAD

**Issue by JaredTheWolf** [DVDAndroid/Xposed-EnableAmbientDisplay#4]
Ambient Display isn't activated on my Moto G 2015 (osprey), 6.0.1, stock. Is it possible that Moto overwrote the files with Moto Display? Because that works perfectly.

**Comment by DVDAndroid** [comment]
Yes, you need to disable moto display. This module cannot disable it.

**Comment by JaredTheWolf** [comment]
I've tried it with Moto Display off, nothing happens.

**Comment by JaredTheWolf** [comment]
Hey, could I get an answer back? I feel as if you closed my issue preemptively.

**Comment by DVDAndroid** [comment]
I cannot fix this problem; however, on Moto devices, there's no need of this module because the differences between Ambient Display and Moto display are equals zero.
I'm sorry I cannot help you

**Comment by JaredTheWolf** [comment]
Alright, I understand. I simply enjoy the Ambient Display aesthetic better,
and it supports Wave to Wake while Moto Display does not. Thank you for
your time.
